### ISSUE TITLE
Build error in extern lib nn = "0.1.5"

### ISSUE THREAD

**Issue by swiesend** [rust-lang/threadpool#9]
Hey out there!

I am very new to rust and still don't know how to tackle building issues. Can someone help me out with this one?

```
RustNN$ cargo build
   Compiling libc v0.1.6
   Compiling rustc-serialize v0.3.14
   Compiling gcc v0.3.5
   Compiling threadpool v0.1.4
   Compiling rand v0.3.8
   Compiling time v0.1.25
   Compiling nn v0.1.5 (file:///home/swiesend/workspace/rust/RustNN)
src/lib.rs:70:18: 70:28 error: unresolved import `threadpool::ScopedPool`. There is no `ScopedPool` in `threadpool`
src/lib.rs:70 use threadpool::{ScopedPool};
                               ^~~~~~~~~~
error: aborting due to previous error
Could not compile `nn`.
```

build is failing with the beta.4 and the nightly build from rust:
```
$ rustc --version
rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)

$ rustc --version
rustc 1.1.0-nightly (c42c1e7a6 2015-05-02) (built 2015-05-02)
```

**Comment by steveklabnik** [comment]
As https://github.com/rust-lang/threadpool/blob/master/src/lib.rs#L173 shows, you need a feature enabled to use `ScopedPool`. This was a recent change, as it was found to be unsound, see all the discussion around Rc and Leak.

Check out http://doc.crates.io/manifest.html#the-[features]-section for an example of how to turn features on in your dependencies. Since this isn't a bug, I'm giving it a close, but if you still can't get it working, feel free to keep commenting, I'll pay attention to the thread.
